# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e61a914e0eb0e835be3fea56d540fcba5fd2a1da48ca8dd4d2229c3943badf7a4b90af5ada5b6ef4673b8fb42a4faa5eeaf8392e785c36a800913b40328d1ce6

test:
  secret_key_base: 3549a5bb56cbc635588cc2f7f367e0244d518d0a9853761cafbe678461b5be4c1e5bc79567a64b4c2c4b3283d8fe7084a26ac5084a3b6371bd493b8263000d37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
